Change import in email_preprocess.py
converting "from sklearn import cross_validation" to "from sklearn.cross_validation import train_test_split", because it was it giving "ImportError: cannot import name cross_validation"