Update email_preprocess.py
converting "from sklearn import cross_validation" to "from sklearn.model_selection import train_test_split", because it was it giving "ImportError: cannot import name cross_validation"